name: Java CI and Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile
      run: |
        mkdir -p out
        javac -d out src/Main.java

    - name: Package JAR
      run: |
        echo 'Main-Class: Main' > manifest.txt
        jar cfm MyJavaApp.jar manifest.txt -C out .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-java-app-jar
        path: MyJavaApp.jar
